using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Simplify.ReactiveUI.Generators;

namespace Simplify.ReactiveUI.Test;

public class VerifyOutput
{
    [Fact]
    public async Task Then_the_expected_output_is_generated()
    {
        var generator = new RegisterGenerator();
        var syntaxTree = CSharpSyntaxTree.ParseText(GetResourceAsString("Address.cs"));
        var compilation = CSharpCompilation.Create(
            nameof(Then_the_expected_output_is_generated),
            [syntaxTree],
            [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)]);
        var driver = CSharpGeneratorDriver.Create(generator)
            .RunGenerators(compilation);
        var result = driver.GetRunResult();
        var output = result.GeneratedTrees.Single(t =>
            t.FilePath.EndsWith("SplatRegisterExtensions.g.cs")).ToString();

        var settings = new VerifySettings();
        settings.ScrubLinesContaining("This code was generated by Simplify.ReactiveUI.Generators.RegisterGenerator");
        settings.UseDirectory("Verify");
        await Verify(output, settings);
    }

    [Fact]
    public async Task Then_the_expected_view_output_is_generated()
    {
        var generator = new RegisterGenerator();
        var viewSyntaxTree = CSharpSyntaxTree.ParseText(GetResourceAsString("TestView.cs"));
        var viewModelSyntaxTree = CSharpSyntaxTree.ParseText(GetResourceAsString("TestViewModel.cs"));
        var compilation = CSharpCompilation.Create(
            nameof(Then_the_expected_view_output_is_generated),
            [viewSyntaxTree, viewModelSyntaxTree],
            [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)]);
        var driver = CSharpGeneratorDriver.Create(generator)
            .RunGenerators(compilation);
        var result = driver.GetRunResult();
        var output = result.GeneratedTrees.Single(t =>
            t.FilePath.EndsWith("SplatRegisterExtensions.g.cs")).ToString();

        var settings = new VerifySettings();
        settings.ScrubLinesContaining("This code was generated by Simplify.ReactiveUI.Generators.RegisterGenerator");
        settings.UseDirectory("Verify");
        await Verify(output, settings);
    }

    private string GetResourceAsString(string resourceName)
    {
        var assembly = typeof(VerifyOutput).Assembly;
        var manifestResourceNames = assembly.GetManifestResourceNames();
        resourceName = manifestResourceNames.Single(x => x.Equals($"Simplify.ReactiveUI.Test.{resourceName}"));

        using var stream = assembly.GetManifestResourceStream(resourceName) ?? throw new Exception();
        using var reader = new StreamReader(stream);

        return reader.ReadToEnd();
    }
}
